#
# Copyright (c) 2022, Scott O'Connor
#

#
# These are subs by year/week for the TNFB.
#

%subs = (
    2020 => {
        1 => { "Carl Humphreys" => "Charlie Weeks",
               "Derek Palatino" => "Paul Correia" },
        2 => { "Derek Palatino" => "Paul Correia" },
        3 => { "Derek Palatino" => "Paul Correia" },
        4 => { "Pat Donahue II" => "Joe Sullivan",
               "Derek Palatino" => "Paul Correia" },
        5 => { "Derek Palatino" => "Paul Correia" },
        6 => { "Derek Palatino" => "Charlie Weeks" },
        7 => { "Jeff LaPlante" => "Mike Perisho" },
        8 => { "Jeff LaPlante" => "Mike Perisho",
               "Carl Humphreys" => "Charlie Weeks" },
        9 => { "Carl Humphreys" => "Charlie Weeks" },
        10 => { "Derek Palatino" => "Marc Foland",
                "Carl Humphreys" => "Charlie Weeks",
                "Brian Sargent" => "Jim Marotta",
                "Leo Palatino" => "Pat Donahue" },
        11 => { "Todd Chapin" => "Paul Sirois",
                "Carl Humphreys" => "Charlie Weeks",
                "Derek Palatino" => "Derek Jodoin" },
        12 => { "Todd Chapin" => "Kevin Cunningham",
                "Jeff LaPlante" => "Jeff Miller" },
        13 => { "Derek Palatino" => "Mike Schmidt",
                "Steve Calvao" => "Kevin Kittredge",
                "Leo Palatino" => "Dan Correia" },
        15 => { "Derek Palatino" => "Bob Tuttle",
                "Steve Calvao" => "Kevin Kittredge" },
    },
    2021 => {
        1 => { "Derek Palatino" => "Dan Correia",
               "Leo Palatino" => "Paul Correia",
               "Ron Melanson" => "Steve Bulawka" },
        2 => { "Derek Palatino" => "Dan Correia",
               "Leo Palatino" => "Paul Correia",
               "Ron Melanson" => "Steve Bulawka" },
        3 => { "Derek Palatino" => "Dan Correia",
               "Leo Palatino" => "Paul Correia",
               "Ron Melanson" => "Steve Bulawka" },
        4 => { "Derek Palatino" => "Dan Correia",
               "Leo Palatino" => "Paul Correia",
               "Alex Williams" => "Marc Foland",
               "Rick Wood" => "Jim O'Keefe",
               "Todd Chapin" => "Derek Jodoin",
               "Ron Melanson" => "Steve Bulawka" },
        5 => { "Derek Palatino" => "Scott O'Connor",
               "Ron Melanson" => "Steve Bulawka" },
        6 => { "Carl Humphreys" => "Charlie Weeks",
               "Ron Melanson" => "Steve Bulawka" },
        7 => { "Ron Melanson" => "Steve Bulawka" },
        8 => { "Benjamin Palatino" => "Mike Gill",
               "Jeff Aucoin" => "Bob Tuttle",
               "Ron Melanson" => "Steve Bulawka" },
        9 => { "Derek Palatino" => "Pat Donahue",
               "Peter Bradley" => "Mike Perisho",
               "Jeff LaPlante" => "Kevin Cunningham",
               "Curt Farnsworth" => "Steve Bulawka" },
        10 => { "Leo Palatino" => "Jim Marotta",
                "Steve Calvao" => "Mike Gill",
                "Rick Wood" => "Jim O'Keefe",
                "Buddy Cuozzo" => "Kevin Cunningham",
                "Paul Rotker" => "Charlie Weeks",
                "Ron Melanson" => "Steve Bulawka",
                "Derek Palatino" => "Dan Correia",
                "Ray Curley" => "Tom Curley" },
        11 => { "Leo Palatino" => "Charlie Weeks",
                "Bill Andon" => "Mike Schmidt",
                "Steve Calvao" => "Randy Carter",
                "Rick Wood" => "Marc Foland",
                "Ron Melanson" => "Steve Bulawka",
                "Derek Palatino" => "Mike Rogers" },
        12 => { "Leo Palatino" => "Paul Sirois",
                "Carl Humphreys" => "Charlie Weeks",
                "Alex Williams" => "Joe Graceffa",
                "Jeff Aucoin" => "Bob Tuttle" },
        13 => { "Leo Palatino" => "Jim Marotta",
                "Carl Humphreys" => "Charlie Weeks",
                "Jeff Aucoin" => "Jeff Miller" },
        14 => { "Pat Donahue II" => "Joe Sullivan",
                "Brian Sargent" => "Tony Albertini",
                "Leo Palatino" => "Paul Sirois",
                "Dave Sherman" => "Larry Fryatt",
                "Ron Melanson" => "John Breslouf",
                "Jeff LaPlante" => "Mike Perisho",
                "Todd Chapin" => "Bob Kilgus",
                "Carl Humphreys" => "Charlie Weeks" },
        15 => { "Bill Andon" => "Charlie Weeks",
                "Leo Palatino" => "Mike Schmidt",
                "Curt Farnsworth" => "John Breslouf",
                "Todd Chapin" => "Bob Kilgus",
                "Buddy Cuozzo" => "Derek Jodoin",
                "Ray Curley" => "Marc Foland" },
    },
    2022 => {
        1 => { "Carl Humphreys" => "Charlie Weeks",
               "Derek Palatino" => "Paul Correia" ,
               "Jeff Aucoin" => "Bob Tuttle" ,
               "Jeff LaPlante" => "Mike Perisho" },
        2 => { "Carl Humphreys" => "Charlie Weeks",
               "Derek Palatino" => "Paul Correia" ,
               "Joe Graceffa" => "Paul Percuoco" ,
               "Jeff LaPlante" => "Mike Perisho" },
        3 => { "Carl Humphreys" => "Charlie Weeks",
               "Derek Palatino" => "Paul Correia" ,
               "Leo Palatino" => "Paul Percuoco" ,
               "Jeff Aucoin" => "Bob Tuttle" },
        4 => { "Carl Humphreys" => "Charlie Weeks",
               "Derek Palatino" => "Paul Percuoco" ,
               "Leo Palatino" => "Chet Czapkowski" ,
               "Todd Chapin" => "Derek Jodoin" ,
               "Joe Graceffa" => "Jeff Miller" ,
               "Jeff LaPlante" => "Bob Tuttle" },
    },
);
