#
# Copyright (c) 2022, 2024 Scott O'Connor
#
# These are subs by year/week for the TNFB.
#

%subs = (
    2003 => {
        1 => { "Alex Williams" => "Charles Nolfi",
               "Al Litchfield" => "Marc Foland",
               "Tom Czarkowski" => "Dave Maruska" },
        2 => { "Tom Czarkowski" => "Paul Correia",
               "Dan Correia" => "Dave O'Donnell",
               "Alex Williams" => "Charles Nolfi",
               "Rick Wood" => "Mike Rogers" },
        3 => { "Mike Baj" => "Charles Nolfi",
               "Dan Correia" => "Marc Foland",
               "Alex Williams" => "Gerry Curley",
               "Tom Czarkowski" => "Wayne Bolivar",
               "Bruce Harris" => "Dan Warila" },
        4 => { "Phil Bonner" => "Tom Curley",
               "Alex Williams" => "Gerry Curley",
               "Dan Correia" => "Dave O'Donnell",
               "Tom Czarkowski" => "Wayne Bolivar",
               "Brian Sargent" => "Marc Foland",
               "Bruce Harris" => "Scott O'Connor",
               "Mike Baj" => "David Treen",
               "Mike Perisho" => "Charles Nolfi" },
        5 => { "Buddy Cuozzo" => "Paul LeBlanc",
               "Mike Perisho" => "Charles Nolfi" },
        6 => { "Paul Chaisson" => "Paul Correia" },
        7 => { "Buddy Cuozzo" => "Jim Marotta",
               "Tom Czarkowski" => "Steve LaRosee" },
        8 => { "Brian Sargent" => "Marc Foland" },
        9 => { "Bruce Harris" => "Marc Foland",
               "John Desisto" => "Charles Nolfi",
               "Alex Williams" => "Paul Correia",
               "Brian Sargent" => "Steve LaRosee",
               "Mike McPoland" => "Dave Maruska" },
        10 => { "Tom Czarkowski" => "Dickie Guild" },
        11 => { "Steve Calvao" => "Leo Palatino",
                "Mark McAleese" => "David Treen",
                "Dan Correia" => "Dave O'Donnell",
                "Tom Czarkowski" => "Dave Maruska",
                "Phil Treen" => "Wayne Bolivar" },
        12 => { "Dan Correia" => "Marc Foland",
                "Joe Berry" => "Dave Petkauskos" },
        13 => { "Joe Berry" => "Dave Petkauskos",
                "Paul Chaisson" => "Paul Correia",
                "Steve Calvao" => "Leo Palatino",
                "Phil Treen" => "David Treen",
                "Dan Correia" => "Dave O'Donnell" },
        14 => { "Dan Correia" => "Dave Maruska",
                "John Desisto" => "Charles Nolfi",
                "Joe Berry" => "Mike Rogers",
                "Alex Williams" => "Tom Rothfuss",
                "Buddy Cuozzo" => "Jim Marotta",
                "Steve Calvao" => "Kevin Kittredge" },
        15 => { "Dan Correia" => "Paul LeBlanc" },
    },
    2004 => {
        1 => { "Dave Maruska" => "Phil Treen",
               "Bill Egan" => "Charlie Bacon",
               "Cliff Calvao" => "Charles Nolfi",
               "Dan Correia" => "John McCauley",
               "Buddy Cuozzo" => "Jim Marotta",
               "Brian Sargent" => "Gerry Curley",
               "David Treen" => "Wayne Bolivar" },
        2 => { "Mike McPoland" => "Wayne Bolivar",
               "Buddy Cuozzo" => "Jim Marotta",
               "Alex Williams" => "Tom Curley",
               "Chris Williams" => "Dan Warila",
               "Brian Sargent" => "Gerry Curley",
               "Dan Correia" => "Marc Foland",
               "Steve Calvao" => "Leo Palatino",
               "Tom Czarkowski" => "Dickie Guild" },
        3 => { "Bruce Harris" => "Marc Foland",
               "Buddy Cuozzo" => "Jim Marotta",
               "Tom Czarkowski" => "Mike Schmidt",
               "David Treen" => "Wayne Bolivar" },
        4 => { "Mike McPoland" => "Phil Treen",
               "Tom Czarkowski" => "Wayne Bolivar",
               "Alex Williams" => "Paul Correia" },
        5 => { "Chris Williams" => "Paul LeBlanc",
               "Alex Williams" => "Dan Warila",
               "David Treen" => "Wayne Bolivar" },
        6 => { "Rick Wood" => "Leo Palatino",
               "Brian Sargent" => "Dave Petkauskos" },
        7 => { "Tom Czarkowski" => "Mike Schmidt",
               "Al Litchfield" => "Wayne Bolivar" },
        8 => { "David Treen" => "Wayne Bolivar",
               "Alex Williams" => "Dan Warila",
               "Tom Czarkowski" => "Mark McAleese",
               "Ken Leigh" => "Tom Rothfuss",
               "Dan Correia" => "Charles Nolfi" },
        9 => { "Cliff Calvao" => "Marc Foland",
               "Dan Correia" => "Dave O'Donnell" },
        10 => { "Dan Correia" => "Paul Correia",
                "Tom Czarkowski" => "Dickie Guild",
                "Mike Perisho" => "Charles Nolfi",
                "Brian Sargent" => "Marc Foland" },
        11 => { "Dan Correia" => "Leo Palatino",
                "David Treen" => "Wayne Bolivar",
                "Mike Perisho" => "Charles Nolfi",
                "Joe Berry" => "Dave Petkauskos" },
        12 => { "Dan Correia" => "Dave O'Donnell",
                "Steve Calvao" => "Vic Billings",
                "Dave Maruska" => "Phil Treen" },
        13 => { "Carl Fryatt" => "Charlie Bacon",
                "Buddy Cuozzo" => "Jim Marotta",
                "Dan Correia" => "Marc Foland" },
        14 => { "Buddy Cuozzo" => "Paul LeBlanc",
                "Dave Maruska" => "Mark McAleese",
                "Steve Calvao" => "Vic Billings",
                "Alex Wz" => "Tom Curley",
                "Dan Correia" => "Dave O'Donnell" },
        15 => { "Dan Correia" => "Tom Rothfuss",
                "Steve Calvao" => "Vic Billings",
                "Dave Maruska" => "Charles Nolfi" },
    },
    2005 => {
        1 => { "Alex Williams" => "Gerry Curley",
               "Brian Sargent" => "Dan Warila",
               "Dan Correia" => "Dave Maruska",
               "Joe Berry" => "Mike Rogers" },
        2 => { "Tom Czarkowski" => "Wayne Bolivar",
               "Mike Elkort" => "Jim Marotta" },
        3 => { "Tom Czarkowski" => "Scott O'Connor",
               "Joe Berry" => "Dave O'Donnell",
               "Alex Williams" => "Gerry Curley",
               "Mike Elkort" => "John Fitzgerald" },
        4 => { "Joe Berry" => "Mike Rogers",
               "Mike Elkort" => "John Fitzgerald",
               "Tom Czarkowski" => "Dave Maruska",
               "Rick Wood" => "Ray Curley",
               "Alex Williams" => "Gerry Curley",
               "Dan Correia" => "Dave O'Donnell" },
        5 => { "Steve Calvao" => "Paul LeBlanc",
               "Alex Williams" => "Jim Marotta",
               "Joe Berry" => "Mike Schmidt",
               "Tom Czarkowski" => "Wayne Bolivar" },
        6 => { "Steve Calvao" => "Jim Marotta",
               "Mike Elkort" => "John Fitzgerald",
               "Joe Berry" => "Mike Rogers",
               "Phil Treen" => "Dave Maruska",
               "Tom Czarkowski" => "Wayne Bolivar" },
        7 => { "Buddy Cuozzo" => "Jim Marotta",
               "David Spurr" => "Mike Perisho",
               "Mike Elkort" => "John Fitzgerald",
               "Dan Correia" => "Paul Correia",
               "Brian Sargent" => "Dave Maruska" },
        8 => { "Leo Palatino" => "Dickie Guild",
               "Dan Correia" => "Charlie Weeks" },
        9 => { "David Spurr" => "Tom Rothfuss",
               "Buddy Cuozzo" => "Mike Suleski",
               "Alex Williams" => "Dan Warila",
               "Mike Elkort" => "Dave Maruska",
               "Dan Correia" => "Mike Schmidt" },
        10 => { "David Treen" => "Wayne Bolivar",
                "Dan Correia" => "John Fitzgerald",
                "Alex Williams" => "Gerry Curley",
                "Steve Calvao" => "Marc Foland" },
        11 => { "Leo Palatino" => "Dave O'Donnell",
                "Phil Treen" => "Mark McAleese",
                "Alex Williams" => "Kevin Crowley",
                "Joe Berry" => "Dave Petkauskos",
                "Steve Calvao" => "Marc Foland" },
        12 => { "Mike Elkort" => "Paul LeBlanc",
                "David Treen" => "Mike Schmidt",
                "Phil Treen" => "Mark McAleese" },
        13 => { "Mike Saliga" => "Pat Donahue",
                "Steve Calvao" => "Gerry Curley",
                "Leo Palatino" => "Dave O'Donnell",
                "Phil Treen" => "John Fitzgerald",
                "Mike Elkort" => "Jim Marotta" },
        14 => { "Steve Calvao" => "Kevin Kittredge",
                "David Treen" => "Dave Petkauskos",
                "Dan Correia" => "Charlie Weeks",
                "Mike Saliga" => "Pat Donahue",
                "Phil Treen" => "Dave O'Donnell",
                "Joe Berry" => "Larry Fryatt",
                "Mike Elkort" => "John Fitzgerald",
                "Leo Palatino" => "Chet Czapkowski" },
        15 => { "Brian Sargent" => "Ray Curley",
                "Dan Correia" => "Mike Perisho",
                "Mike Elkort" => "Paul LeBlanc",
                "Tom Czarkowski" => "Dave Maruska",
                "Phil Treen" => "Pat Donahue",
                "Joe Berry" => "Mike Rogers",
                "David Treen" => "John Fitzgerald",
                "Leo Palatino" => "Chet Czapkowski" },
    },
    2006 => {
        1 => { "Leo Palatino" => "Paul Correia",
               "Rick Wood" => "Dave O'Donnell",
               "Brian Sargent" => "Kevin Crowley",
               "Buddy Cuozzo" => "Jim Marotta",
               "Mike Elkort" => "Wayne Bolivar",
               "Steve Calvao" => "Vic Billings" },
        2 => { "Alex Williams" => "Ray Curley",
               "Dan Correia" => "Mike Perisho",
               "Buddy Cuozzo" => "John Fitzgerald",
               "Tom Czarkowski" => "Mark McAleese" },
        3 => { "Tom Czarkowski" => "Scott O'Connor",
               "Andy Treen" => "David Treen",
               "Dan Correia" => "Dave Maruska" },
        4 => { "Tom Czarkowski" => "Dave Maruska",
               "Dan Correia" => "Wayne Bolivar",
               "Brian Sargent" => "Chet Czapkowski",
               "Steve Cerven" => "Tom Rothfuss",
               "Alex Williams" => "Jim Marotta",
               "Andy Treen" => "David Treen" },
        5 => { "Gerry Curley" => "Marc Foland",
               "Mike Elkort" => "Jim Marotta",
               "Jeff Kerrigan" => "Wayne Bolivar" },
        6 => { "Alex Williams" => "Ray Curley",
               "Dan Correia" => "Paul Correia",
               "Steve Calvao" => "Dave O'Donnell",
               "Tom Czarkowski" => "Mike Schmidt" },
        7 => { "Alex Williams" => "Kevin Crowley",
               "Steve Calvao" => "Dickie Guild",
               "Buddy Cuozzo" => "John Fitzgerald",
               "Dan Correia" => "Mike Perisho" },
        8 => { "Brian Sargent" => "Marc Foland",
               "Dan Correia" => "Mike Schmidt" },
        9 => { "Tom Czarkowski" => "Dave Maruska",
               "Joe Berry" => "Mike Saliga",
               "Dan Correia" => "Jim Marotta",
               "Buddy Cuozzo" => "Paul LeBlanc",
               "Matt Herring" => "Dave O'Donnell",
               "Steve Willey" => "Charlie Bacon" },
        10 => { "Steve Calvao" => "Marc Foland",
                "Alex Williams" => "Kevin Crowley",
                "Dan Correia" => "Tom Rothfuss",
                "Mike Elkort" => "Mike Schmidt",
                "Tom Czarkowski" => "Dickie Guild" },
        11 => { "Gerry Curley" => "Tom Curley",
                "Brian Sargent" => "Marc Foland" },
        12 => { "Ryan Abrams" => "Charlie Weeks",
                "Buddy Cuozzo" => "Paul LeBlanc",
                "Dan Correia" => "Dave O'Donnell",
                "Steve Willey" => "Larry Fryatt",
                "Alex Williams" => "Kevin Kittredge" },
        13 => { "Brian Sargent" => "Chet Czapkowski",
                "Ken Pesanelli" => "Mike Perisho",
                "Tom Czarkowski" => "Dave Maruska",
                "Paul Percuoco" => "David Treen",
                "Joe Berry" => "Mike Rogers",
                "Buddy Cuozzo" => "John Fitzgerald",
                "Dan Correia" => "Dave O'Donnell",
                "Alex Williams" => "Kevin Kittredge" },
        14 => { "Jeff Kerrigan" => "Wayne Bolivar",
                "Mike Elkort" => "Charlie Weeks",
                "Gerry Curley" => "Marc Foland",
                "Carl Fryatt" => "Charlie Bacon",
                "Ken Pesanelli" => "Mike Perisho",
                "Steve Calvao" => "Paul Correia" },
        15 => { "Dan Correia" => "Dave O'Donnell",
                "Ken Pesanelli" => "Mike Perisho",
                "Tom Czarkowski" => "Phil Treen",
                "Alex Williams" => "Dave Maruska" },
    },
    2007 => {
        1 => { "Steve Calvao" => "Vic Billings",
               "Mike Elkort" => "Jim Marotta",
               "Phil Treen" => "Wayne Bolivar" },
        2 => { "Cliff Calvao" => "Kevin Crowley",
               "Mike Elkort" => "Mike Suleski",
               "Tom Czarkowski" => "Dave Maruska" },
        3 => { "David Treen" => "Wayne Bolivar",
               "Mike McPoland" => "Dave Maruska",
               "Brian Sargent" => "Kevin Crowley",
               "Steve Calvao" => "Mike Gill",
               "Dave Petkauskos" => "Mike Rogers",
               "Leo Palatino" => "Dan Correia",
               "Phil Treen" => "Paul Correia" },
        4 => { "Phil Treen" => "Mark McAleese",
               "Steve Calvao" => "Chet Czapkowski",
               "Brian Sargent" => "Kevin Crowley" },
        5 => { "Steve Calvao" => "Kevin Crowley",
               "Mike Elkort" => "Jim Marotta",
               "Phil Treen" => "Dave O'Donnell" },
        6 => { "Dave Petkauskos" => "Andrew Goddard",
               "David Treen" => "Wayne Bolivar",
               "Phil Treen" => "Mark McAleese",
               "Tom Czarkowski" => "Dave Maruska",
               "Steve Calvao" => "Marc Foland",
               "Brian Sargent" => "Kevin Crowley" },
        7 => { "Buddy Cuozzo" => "Mike Suleski",
               "Phil Treen" => "Dave Maruska",
               "Brian Sargent" => "Kevin Crowley" },
        8 => { "Dave Petkauskos" => "Dave O'Donnell",
               "Tom Czarkowski" => "Dave Maruska",
               "Dickie Guild" => "Ray Curley",
               "Cliff Calvao" => "Kevin Crowley" },
        9 => { "Phil Treen" => "Scott O'Connor",
               "David Treen" => "Mark McAleese",
               "Dave Petkauskos" => "John McCauley",
               "Brian Sargent" => "Paul LeBlanc",
               "Al Litchfield" => "Marc Foland",
               "Cliff Calvao" => "Kevin Crowley" },
        10 => { "Brian Sargent" => "Kevin Crowley",
                "Dave Petkauskos" => "Dave O'Donnell",
                "Phil Treen" => "Mark McAleese",
                "Tom Czarkowski" => "Mike Schmidt",
                "Steve Willey" => "Charlie Bacon" },
        11 => { "Brian Sargent" => "Jim Marotta" },
        12 => { "Dickie Guild" => "Tom Curley",
                "Leo Palatino" => "Ray Curley",
                "Dan Weilandt" => "Mike Perisho",
                "Mike Elkort" => "John Fitzgerald",
                "Steve Willey" => "Charlie Bacon" },
        13 => { "Tom Czarkowski" => "Charlie Weeks",
                "Dave Petkauskos" => "Dave O'Donnell",
                "Mike Elkort" => "Mike Schmidt" },
        14 => { "Steve Willey" => "Larry Fryatt",
                "Mike Elkort" => "Jim Marotta",
                "John Desisto" => "Tom Rothfuss",
                "Ken Pesanelli" => "Mike Perisho",
                "Steve Calvao" => "Kevin Kittredge" },
        15 => { "Mike Elkort" => "Wayne Bolivar",
                "Dave Petkauskos" => "Mike Rogers",
                "Tom Czarkowski" => "Dave O'Donnell" },
    },
    2008 => {
        1 => { "Leo Palatino" => "Paul Correia",
               "Steve Willey" => "Charlie Bacon",
               "Rick Wood" => "Kevin Kittredge" },
        2 => { "Rick Wood" => "Kevin Kittredge",
               "Tom Czarkowski" => "Grant Everett",
               "Joe Berry" => "Mike Rogers" },
        3 => { "Rick Wood" => "Kevin Kittredge",
               "Buddy Cuozzo" => "Mike Suleski" },
        4 => { "Rick Wood" => "Kevin Kittredge",
               "Leo Palatino" => "Paul Correia",
               "Tim Gleason" => "Andrew Goddard",
               "Tom Czarkowski" => "Wayne Bolivar" },
        5 => { "Brian Sargent" => "Jim Marotta",
               "Tom Czarkowski" => "Wayne Bolivar",
               "David Treen" => "Dave Maruska",
               "Tim Gleason" => "Andrew Goddard",
               "Leo Palatino" => "Dave O'Donnell" },
        6 => { "Tim Gleason" => "Andrew Goddard",
               "Phil Treen" => "Mark McAleese",
               "Tom Czarkowski" => "Dave Maruska" },
        7 => { "Phil Treen" => "Dave O'Donnell",
               "Tom Czarkowski" => "Dave Maruska",
               "Gerry Curley" => "Mike Gill" },
        8 => { "Steve Willey" => "Charlie Bacon",
               "Phil Treen" => "Mark McAleese",
               "Rick Wood" => "Kevin Kittredge" },
        9 => { "Tom Czarkowski" => "Wayne Bolivar",
               "Gerry Curley" => "Ray Curley",
               "Dickie Guild" => "Paul Giancola" },
        10 => { },
        11 => { "Phil Treen" => "Ray Emond",
                "Tom Czarkowski" => "Charlie Weeks",
                "Dickie Guild" => "Dave Petkauskos",
                "Leo Palatino" => "Ray Curley" },
        12 => { "Dickie Guild" => "Mike Rogers",
                "Phil Treen" => "Dave Maruska" },
        13 => { "Tom Czarkowski" => "Grant Everett",
                "Dan Weilandt" => "Tom Rothfuss",
                "Brian Sargent" => "Chet Czapkowski",
                "Leo Palatino" => "Jim Marotta",
                "Dickie Guild" => "Paul Giancola",
                "Phil Treen" => "Dave O'Donnell",
                "Tim Gleason" => "Andrew Goddard",
                "Gerry Curley" => "Tom Curley",
                "Jeff Kerrigan" => "Wayne Bolivar" },
        14 => { "Cliff Calvao" => "Dan Correia",
                "Leo Palatino" => "Tom Curley",
                "Steve Willey" => "Larry Fryatt",
                "Dan Weilandt" => "Mike Perisho",
                "Rick Wood" => "Kevin Kittredge" },
        15 => { "Bill Tobey" => "Charlie Bacon",
                "Dan Weilandt" => "Mike Perisho",
                "Tom Czarkowski" => "Wayne Bolivar" },
    },
    2009 => {
        1 => { "Chris DiSilva" => "Charlie Bacon",
               "Leo Palatino" => "Dave O'Donnell" },
        2 => { "Alex Williams" => "Jim Marotta",
               "David Treen" => "Paul Correia",
               "Brian Sargent" => "Dave O'Donnell",
               "Dan Weilandt" => "Tom Rothfuss",
               "Phil Treen" => "Mark McAleese",
               "Leo Palatino" => "Mark Starr",
               "Tom Czarkowski" => "Dave Maruska" },
        3 => { "Alex Williams" => "Tom Curley",
               "Joe Berry" => "Dave Petkauskos",
               "Tom Czarkowski" => "Dave Maruska" },
        4 => { "Rick Wood" => "Pat Donahue",
               "Steve Calvao" => "Andrew Goddard",
               "Chris DiSilva" => "Larry Fryatt",
               "Alex Williams" => "Jim Marotta" },
        5 => { "Steve Calvao" => "Mike Suleski" },
        6 => { "David Treen" => "Wayne Bolivar",
               "Tom Czarkowski" => "Dave Maruska",
               "Phil Treen" => "Grant Everett" },
        7 => { "Rick Wood" => "Joe Sullivan",
               "Leo Palatino" => "Andrew Goddard",
               "David Treen" => "Charlie Weeks" },
        8 => { "Dan Weilandt" => "Mike Perisho",
               "Steve Calvao" => "Mike Suleski",
               "Jeff Kerrigan" => "Wayne Bolivar",
               "Leo Palatino" => "Dan Correia",
               "Phil Treen" => "Mark McAleese",
               "David Treen" => "Dave Petkauskos" },
        9 => { "Phil Treen" => "Dave O'Donnell",
               "Brian Sargent" => "Marc Foland",
               "Rick Wood" => "Ray Curley",
               "Joe Berry" => "Dave Petkauskos",
               "Tom Czarkowski" => "Dave Maruska" },
        10 => { "Rick Wood" => "Ray Curley" },
        11 => { "Leo Palatino" => "Dave O'Donnell",
                "Dan Weilandt" => "Tom Rothfuss",
                "Brian Sargent" => "Jim Marotta",
                "Rick Wood" => "Ray Curley",
                "Ray Emond" => "Steve LaRosee",
                "David Treen" => "Mike Schmidt" },
        12 => { "Chris DiSilva" => "Charlie Bacon",
                "Chris DiSilva Sr" => "Larry Fryatt",
                "Brian Sargent" => "Marc Foland",
                "Rick Wood" => "Ray Curley",
                "Steve Calvao" => "Kevin Kittredge",
                "Leo Palatino" => "Mark Starr",
                "Dickie Guild" => "Dave Petkauskos" },
        13 => { "Chris Williams" => "Chet Czapkowski",
                "Alex Williams" => "Jim Marotta",
                "Tom Czarkowski" => "Marc Foland",
                "Chris DiSilva" => "Larry Fryatt",
                "Rick Wood" => "Ray Curley",
                "Steve Calvao" => "Joe Sullivan",
                "Ken Pesanelli" => "Mike Perisho" },
        14 => { "Rick Wood" => "Ray Curley",
                "Dan Weilandt" => "Mike Perisho",
                "Brian Sargent" => "Marc Foland",
                "Leo Palatino" => "Dave O'Donnell",
                "Alex Williams" => "Kevin Kittredge" },
        15 => { "Dickie Guild" => "Dave Petkauskos",
                "Leo Palatino" => "Dave O'Donnell",
                "Rick Wood" => "Ray Curley",
                "Phil Treen" => "Mark McAleese",
                "Steve Calvao" => "Pat Donahue" },
    },
    2010 => {
        1 => { "Cliff Calvao" => "Mike Gill",
               "Leo Palatino" => "Jim Marotta" },
        2 => { "Cliff Calvao" => "Chet Czapkowski",
               "Dan Weilandt" => "Eric Ogren",
               "Leo Palatino" => "Pat Donahue",
               "Dave O'Donnell" => "Paul Correia",
               "Andrew Goddard" => "Dan Correia" },
        3 => { "Alex Williams" => "Ed Reverdy",
               "Cliff Calvao" => "Scott O'Connor",
               "Brian Sargent" => "Mark McAleese" },
        4 => { "David Treen" => "Charlie Weeks",
               "Leo Palatino" => "Mark Starr",
               "Cliff Calvao" => "Ed Reverdy" },
        5 => { "Leo Palatino" => "Pat Donahue" },
        6 => { "Alex Williams" => "Eric Ogren" },
        7 => { "Leo Palatino" => "Mike Suleski",
               "Bobby Kilgus" => "Mark McAleese",
               "Tom Rothfuss" => "Paul Sirois" },
        8 => { "Bobby Kilgus" => "Mark McAleese",
               "Cliff Calvao" => "Ed Reverdy",
               "Mike Perisho" => "Paul Sirois",
               "Leo Palatino" => "Mike Schmidt" },
        9 => { "Alex Williams" => "Jim Marotta",
               "Cliff Calvao" => "Ed Reverdy" },
        10 => { "Chris Williams" => "Paul Correia",
                "Bobby Kilgus" => "Mark McAleese",
                "Alex Williams" => "Vic Billings",
                "Cliff Calvao" => "Pat Donahue" },
        11 => { "Alex Williams" => "Mark McAleese",
                "Leo Palatino" => "Pat Donahue",
                "Tom Rothfuss" => "Ed Reverdy" },
        12 => { "Cliff Calvao" => "Rick Wood",
                "Alex Williams" => "Steve Calvao",
                "Paul Percuoco" => "Scott O'Connor",
                "David Treen" => "Mark McAleese",
                "Tom Czarkowski" => "Jim Marotta" },
        13 => { "Tom Rothfuss" => "Pete Linstrom",
                "Leo Palatino" => "Charlie Weeks" },
        14 => { "Tom Rothfuss" => "Pete Linstrom",
                "Mike Perisho" => "Paul Sirois",
                "Leo Palatino" => "Mike Rogers",
                "Paul Percuoco" => "Joe Thoman",
                "Cliff Calvao" => "Rick Wood",
                "Alex Williams" => "Steve Calvao",
                "Wayne Bolivar" => "Charlie Weeks" },
        15 => { "Cliff Calvao" => "Kevin Kittredge",
                "Buddy Cuozzo" => "John Fitzgerald",
                "Chris DiSilva" => "Larry Fryatt" },
    },
    2011 => {
        1 => { },
        2 => { "Brian Sargent" => "Jim Marotta",
               "Steve Calvao" => "Bobby Kilgus",
               "Leo Palatino" => "Paul Correia",
               "David Treen" => "Eric Ogren",
               "Dave O'Donnell" => "Dan Correia" },
        3 => { "Joe Thoman" => "Scott O'Connor",
               "Leo Palatino" => "Eric Ogren",
               "Scott Fairbairn" => "Mark Starr" },
        4 => { "Mark McAleese" => "Scott O'Connor",
               "Leo Palatino" => "Mike Schmidt",
               "Cliff Calvao" => "Ed Reverdy",
               "Dave Sherman" => "Charlie Bacon" },
        5 => { "Cliff Calvao" => "Tom Curley",
               "Leo Palatino" => "Mike Rogers",
               "Brian Sargent" => "Chet Czapkowski",
               "Alex Williams" => "Jim Marotta" },
        6 => { "Alex Williams" => "Jim Marotta",
               "Leo Palatino" => "Tom Rothfuss",
               "Cliff Calvao" => "Ed Reverdy",
               "Steve Calvao" => "John Fitzgerald" },
        7 => { "Alex Williams" => "Ray Curley",
               "Buddy Cuozzo" => "John Fitzgerald",
               "Steve Calvao" => "Paul Sirois" },
        8 => { "Alex Williams" => "Vic Billings",
               "Ken Pesanelli" => "Mike Perisho",
               "Mike Elkort" => "John Fitzgerald",
               "Cliff Calvao" => "Chet Czapkowski",
               "Brian Sargent" => "Tom Curley" },
        9 => { "Scott Fairbairn" => "Mark Starr",
               "Cliff Calvao" => "Chet Czapkowski",
               "Mike Elkort" => "John Fitzgerald" },
        10 => { "Alex Williams" => "Vic Billings" },
        11 => { "Dave Petkauskos" => "John Maley",
                "David Treen" => "John Fitzgerald",
                "Ken Pesanelli" => "Mike Perisho" },
        12 => { "Dave Sherman" => "Larry Fryatt",
                "Cliff Calvao" => "Paul Sirois",
                "Leo Palatino" => "John Fitzgerald",
                "Ken Pesanelli" => "Tom Rothfuss" },
        13 => { "Ken Pesanelli" => "Eric Ogren",
                "Mike Elkort" => "John Fitzgerald" },
        14 => { "Dave Petkauskos" => "Mike Rogers",
                "Leo Palatino" => "Dan Correia",
                "Tom Czarkowski" => "Mike Schmidt",
                "Mike Elkort" => "John Fitzgerald",
                "Ken Pesanelli" => "Mike Perisho" },
        15 => { "Mike Elkort" => "John Fitzgerald",
                "Dave Sherman" => "Larry Fryatt",
                "Alex Williams" => "Kevin Kittredge",
                "Brian Sargent" => "Marc Foland",
                "Cliff Calvao" => "Derek Jodoin",
                "Scott Fairbairn" => "Mark Starr" },
    },
    2012 => {
        1 => { "Joe Thoman" => "Scott O'Connor",
               "Leo Palatino" => "Mike Schmidt",
               "Scott Fairbairn" => "Robert Reslow" },
        2 => { "Scott Fairbairn" => "Robert Reslow",
               "Alex Williams" => "Marc Foland",
               "Joe Thoman" => "Scott O'Connor" },
        3 => { "Brian Sargent" => "Marc Foland",
               "Alex Williams" => "Paul Sirois" },
        4 => { "Alex Williams" => "Marc Foland",
               "Ken Pesanelli" => "Tom Rothfuss" },
        5 => { "Cliff Calvao" => "Pat Donahue",
               "Chris DiSilva" => "Charlie Bacon",
               "Alex Williams" => "Paul Correia",
               "John Fitzgerald" => "Joe Flannery",
               "Steve Calvao" => "Dan Correia" },
        6 => { "Mark Donahue" => "Tom Rothfuss",
               "Gerry Curley" => "Ray Curley",
               "Cliff Calvao" => "Ed Reverdy" },
        7 => { "Alex Williams" => "Jim Marotta",
               "Rick Wood" => "Pat Donahue",
               "Steve Calvao" => "Joe Flannery" },
        8 => { "Cliff Calvao" => "Joe Flannery",
               "Mark Donahue" => "Pat Donahue" },
        9 => { "Mark Donahue" => "Pat Donahue" },
        10 => { "Cliff Calvao" => "Jim Marotta",
                "Tom Czarkowski" => "Mike Schmidt",
                "Mark Donahue" => "Joe Sullivan",
                "Brian Sargent" => "Tom Curley",
                "Buddy Cuozzo" => "Joe Flannery",
                "Rick Wood" => "Vic Billings",
                "Paul Percuoco" => "Scott O'Connor",
                "Steve Calvao" => "Pete Linstrom" },
        11 => { "Rick Wood" => "Pat Donahue",
                "Jim Gregg" => "Ed Reverdy",
                "Dave Sherman" => "Charlie Bacon" },
        12 => { "Leo Palatino" => "Mike Rogers",
                "Brian Sargent" => "Mike Schmidt" },
        13 => { "Cliff Calvao" => "Ed Reverdy",
                "Ken Pesanelli" => "Mike Perisho",
                "Paul Percuoco" => "Bobby Kilgus",
                "Alex Williams" => "Paul Sirois",
                "Rick Wood" => "Pat Donahue" },
        14 => { "Jim Gregg" => "Bobby Kilgus",
                "Scott Fairbairn" => "John Breslouf",
                "Ken Pesanelli" => "Mike Perisho",
                "Alex Williams" => "Ray Curley",
                "Mark Donahue" => "Scott O'Connor" },
        15 => { "Jim Gregg" => "Pete Linstrom",
                "Alex Williams" => "Vic Billings",
                "Scott Fairbairn" => "Robert Reslow",
                "Cliff Calvao" => "Kevin Kittredge" },
    },
    2013 => {
        1 => { },
        2 => { "Chris DiSilva" => "Charlie Bacon",
               "Steve Calvao" => "Pat Donahue",
               "Alex Williams" => "Paul Sirois",
               "Leo Palatino" => "Paul Correia" },
        3 => { "Jim Gregg" => "Eric Ogren" },
        4 => { "Dave O'Donnell" => "Dan Correia",
               "Rick Wood" => "Pat Donahue",
               "Alex Williams" => "Eric Ogren" },
        5 => { "Brian Sargent" => "Charlie Weeks",
               "Rick Wood" => "Mike Gill" },
        6 => { "Jim Gregg" => "Ed Reverdy" },
        7 => { "Alex Williams" => "Vic Billings",
               "Paul Percuoco" => "Scott O'Connor",
               "Brian Sargent" => "Mike Schmidt" },
        8 => { "Alex Williams" => "Paul Sirois",
               "Brian Sargent" => "Mike Schmidt" },
        9 => { "Buddy Cuozzo" => "Mike Suleski",
               "Brian Sargent" => "Chet Czapkowski",
               "Cliff Calvao" => "Tom Curley",
               "Rick Wood" => "Pat Donahue",
               "Alex Williams" => "Tom Rothfuss",
               "Jim Gregg" => "Ed Reverdy" },
        10 => { "Cliff Calvao" => "Ray Curley" },
        11 => { "Rick Wood" => "Pat Donahue",
                "Leo Palatino" => "Ed Reverdy" },
        12 => { "Brian Sargent" => "Derek Jodoin",
                "Leo Palatino" => "Pat Donahue" },
        13 => { "Steve Calvao" => "Marc Foland",
                "Rick Wood" => "Pat Donahue" },
        14 => { "Brian Sargent" => "Bobby Kilgus",
                "Paul Percuoco" => "Pat Donahue",
                "Alex Williams" => "Kevin Kittredge",
                "Tim Benson" => "Paul Sirois",
                "Rick Dowen" => "Mike Rogers",
                "Joe Thoman" => "Scott O'Connor" },
        15 => { "Brian Sargent" => "Mike Schmidt",
                "Alex Williams" => "Paul Sirois",
                "Rick Wood" => "Pat Donahue" },
    },
    2014 => {
        1 => { "Brian Sargent" => "Ed Reverdy",
               "Carl Humphreys" => "Charlie Weeks" },
        2 => { "Alex Williams" => "Paul Sirois",
               "Mike Manere" => "Bobby Kilgus" },
        3 => { "Rick Wood" => "Pat Donahue",
               "Paul Percuoco" => "Phil Treen" },
        4 => { "Vic Billings" => "Tony Albertini",
               "Alex Williams" => "Paul Sirois",
               "Paul Percuoco" => "Phil Treen" },
        5 => { "Leo Palatino" => "Paul Correia",
               "Paul Percuoco" => "Joe Sullivan",
               "David Correia" => "Dan Correia" },
        6 => { "Steve Calvao" => "Kevin Cunningham" },
        7 => { "Phil Doe" => "Joe Flannery",
               "Paul Percuoco" => "Paul Sirois",
               "Leo Palatino" => "Pat Donahue",
               "David Correia" => "Paul Correia" },
        8 => { "Scott Fairbairn" => "John Breslouf" },
        9 => { "Paul Percuoco" => "Pat Donahue" },
        10 => { "Paul Percuoco" => "Mike Gill",
                "Alex Williams" => "Pete Linstrom",
                "Brian Sargent" => "Ed Reverdy",
                "David Correia" => "Paul Correia" },
        11 => { "Phil Summers" => "Mike Suleski",
                "Alex Williams" => "Ed Reverdy" },
        12 => { "Leo Palatino" => "Steve Bulawka",
                "Paul Percuoco" => "Mike Gill",
                "Mark Donahue" => "Pat Donahue",
                "Alex Williams" => "Kevin Cunningham" },
        13 => { "Alex Williams" => "Mike Perisho",
                "Steve Calvao" => "Kevin Cunningham",
                "Brian Sargent" => "Jeff Miller",
                "Paul Percuoco" => "Marc Foland",
                "Joe Graceffa" => "Tony Albertini" },
        14 => { "Eric Ogren" => "Derek Jodoin",
                "Mark Donahue" => "Pat Donahue",
                "Brian Sargent" => "Jeff Miller",
                "Steve Calvao" => "Mike Perisho",
                "Joe Graceffa" => "Tony Albertini",
                "Vic Billings" => "Kevin Kittredge",
                "Paul Percuoco" => "Mike Rogers" },
        15 => { "Mark Donahue" => "Pat Donahue",
                "David Correia" => "Paul Correia",
                "Bob Sherman" => "Larry Fryatt",
                "Brian Sargent" => "Bobby Kilgus" },
    },
    2015 => {
        1 => { "David Correia" => "Dan Correia" },
        2 => { "Dave O'Donnell" => "Paul Correia" },
        3 => { "Brian Sargent" => "Ed Reverdy",
               "Alex Williams" => "Paul Sirois",
               "Mark Donahue" => "Derek Jodoin" },
        4 => { "Dave O'Donnell" => "Paul Correia" },
        5 => { "Brian Sargent" => "Mike Gill",
               "Joe Graceffa" => "Ray Curley" },
        6 => { "Alex Williams" => "Mike Perisho",
               "Brian Sargent" => "Ed Reverdy",
               "Paul Percuoco" => "Derek Jodoin",
               "Mark Donahue" => "Pat Donahue",
               "David Correia" => "Paul Correia" },
        7 => { "Rick Wood" => "Pat Donahue",
               "Alex Williams" => "Paul Sirois" },
        8 => { "Alex Williams" => "Kevin Cunningham",
               "Brian Sargent" => "Mike Suleski",
               "Rick Wood" => "Kevin Kittredge" },
        9 => { "Rick Wood" => "Pat Donahue",
               "Tom Rothfuss" => "Kevin Cunningham" },
        10 => { "Rick Wood" => "Pat Donahue",
                "Alex Williams" => "Kevin Cunningham" },
        11 => { "Cliff Calvao" => "Chet Czapkowski",
                "Carl Humphreys" => "Charlie Weeks",
                "Mark Donahue" => "Pat Donahue",
                "Eric Ogren" => "Pete Linstrom",
                "Alex Williams" => "Mike Perisho" },
        12 => { "Brian Sargent" => "Chet Czapkowski",
                "Leo Palatino" => "Jeff Miller",
                "Alex Williams" => "Mike Perisho",
                "Rick Wood" => "Tom Curley" },
        13 => { "Eric Ogren" => "Jeff Miller",
                "Brian Sargent" => "Chet Czapkowski",
                "Rick Wood" => "Marc Foland" },
        14 => { "Brian Sargent" => "Mike Schmidt",
                "Bob Mauro" => "Larry Fryatt",
                "Mark Donahue" => "Mike Rogers",
                "Scott Fairbairn" => "Steve Bulawka",
                "Joe Graceffa" => "Tom Curley" },
        15 => { "Mark Donahue" => "Pat Donahue",
                "Brian Sargent" => "Bobby Kilgus",
                "Eric Ogren" => "Ed Reverdy",
                "Leo Palatino" => "Ray Curley",
                "Joe Graceffa" => "Mike Gill" },
    },
    2016 => {
        1 => { },
        2 => { "Alex Williams" => "Kevin Cunningham",
               "Brian Sargent" => "Mike Gill" },
        3 => { "Leo Palatino" => "Joe Sullivan" },
        4 => { "Leo Palatino" => "Eric Ogren" },
        5 => { "Brian Sargent" => "Eric Ogren",
               "Rick Wood" => "Mike Gill" },
        6 => { "Leo Palatino" => "Tom Curley" },
        7 => { "Alex Williams" => "Mike Perisho",
               "Rick Wood" => "Marc Foland",
               "Paul Percuoco" => "Pat Donahue" },
        8 => { "Rick Wood" => "Joe Sullivan",
               "Paul Percuoco" => "Pat Donahue",
               "Brian Sargent" => "Derek Jodoin" },
        9 => { "Brian Sargent" => "Chet Czapkowski",
               "David Correia" => "Joe Flannery",
               "Paul Percuoco" => "Mike Schmidt" },
        10 => { "Rick Wood" => "Kevin Kittredge",
                "Gerry Curley" => "Marc Foland" },
        11 => { "David Correia" => "Dan Correia" },
        12 => { "Alex Williams" => "Paul Sirois",
                "Brian Sargent" => "Mike Perisho",
                "Paul Percuoco" => "Kevin Cunningham" },
        13 => { "Alex Williams" => "Mike Perisho",
                "Leo Palatino" => "Dan Correia",
                "Brian Sargent" => "Marc Foland" },
        14 => { "Paul Percuoco" => "Eric Ogren",
                "Alex Williams" => "Mike Perisho",
                "Mark Donahue" => "Mike Rogers" },
        15 => { "Alex Williams" => "Pete Linstrom",
                "Leo Palatino" => "Marc Foland",
                "Paul Percuoco" => "Bobby Kilgus",
                "Brian Sargent" => "Jeff Miller" },
    },
    2017 => {
        1 => { },
        2 => { },
        3 => { "Dave Sherman" => "Charlie Bacon" },
        4 => { "Rick Wood" => "Paul Sirois",
               "Steve Calvao" => "Jim O'Keefe" },
        5 => { },
        6 => { "Leo Palatino" => "Dan Correia",
               "Cliff Calvao" => "Jim Marotta" },
        7 => { "Leo Palatino" => "Pat Donahue",
               "David Correia" => "Dan Correia" },
        8 => { "Rick Wood" => "Randy Carter" },
        9 => { "Alex Williams" => "Kevin Cunningham",
               "Brian Sargent" => "Charlie Weeks" },
        10 => { "Brian Sargent" => "Paul Sirois",
                "Leo Palatino" => "Joe Sullivan" },
        11 => { "Buddy Cuozzo" => "Derek Jodoin",
                "David Correia" => "Dan Correia",
                "Brian Sargent" => "Eric Ogren" },
        12 => { "David Correia" => "Dan Correia",
                "Brian Sargent" => "Marc Foland" },
        13 => { "Dave Sherman" => "Larry Fryatt",
                "Steve Calvao" => "Randy Carter",
                "Todd Chapin" => "Bobby Kilgus",
                "Alex Williams" => "Mike Perisho",
                "Brian Sargent" => "Jeff Miller" },
        14 => { "Todd Chapin" => "Bobby Kilgus",
                "David Correia" => "Derek Jodoin",
                "Scott Fairbairn" => "Steve Bulawka",
                "Alex Williams" => "Kevin Cunningham",
                "Brian Sargent" => "Jeff Miller" },
        15 => { "Steve Calvao" => "Jim O'Keefe",
                "Alex Williams" => "Mike Rogers",
                "David Correia" => "Dan Correia",
                "Brian Sargent" => "Marc Foland" },
    },
    2018 => {
        1 => { "Carl Humphreys" => "Charlie Weeks",
               "Brian Sargent" => "Paul Sirois",
               "Steve Calvao" => "Randy Carter" },
        2 => { "Steve Calvao" => "Randy Carter",
               "Alex Williams" => "Pat Donahue" },
        3 => { "John Emerson" => "Phil Treen",
               "Leo Palatino" => "Chet Czapkowski",
               "Todd Chapin" => "Derek Jodoin",
               "Steve Calvao" => "Randy Carter" },
        4 => { "Todd Chapin" => "Derek Jodoin" },
        5 => { },
        6 => { "Paul Percuoco" => "John Breslouf",
               "Alex Williams" => "Mike Perisho" },
        7 => { "Rick Wood" => "Pat Donahue",
               "Leo Palatino" => "Paul Correia",
               "Todd Chapin" => "Derek Jodoin" },
        8 => { "Rick Wood" => "Joe Sullivan",
               "Todd Chapin" => "Bobby Kilgus",
               "Paul Percuoco" => "Jeff Miller" },
        9 => { "Leo Palatino" => "Dan Correia",
               "Joe Graceffa" => "Tony Albertini",
               "Paul Percuoco" => "Scott O'Connor",
               "Todd Chapin" => "Bobby Kilgus",
               "Jay Fredette" => "Randy Carter",
               "Steve Calvao" => "Mike Schmidt" },
        10 => { "Jeff LaPlante" => "Mike Perisho",
                 "Brian Sargent" => "Kevin Cunningham",
                 "Dave Sherman" => "Charlie Bacon",
                 "Rick Wood" => "Tom Curley",
                 "Alex Williams" => "Ray Curley",
                 "Paul Percuoco" => "Scott O'Connor",
                 "Leo Palatino" => "Mike Gill" },
        11 => { "Leo Palatino" => "Dan Correia",
                 "Rick Wood" => "Pat Donahue",
                 "Alex Williams" => "Mike Perisho" },
        12 => { "Brian Sargent" => "Jeff Miller",
                 "Alex Williams" => "Mike Perisho",
                 "John Emerson" => "Scott O'Connor" },
        13 => { "Todd Chapin" => "Derek Jodoin",
                 "Brian Sargent" => "Jeff Miller",
                 "Dave Sherman" => "Charlie Bacon",
                 "Bob Mauro" => "Larry Fryatt",
                 "Joe Graceffa" => "Tony Albertini",
                 "Alex Williams" => "Kevin Kittredge",
                 "Paul Percuoco" => "Paul Sirois" },
        14 => { "Jeff Aucoin" => "Jeff Miller",
                 "Alex Williams" => "Mike Rogers",
                 "Jay Fredette" => "Jim O'Keefe",
                 "Todd Chapin" => "Bobby Kilgus",
                 "Rick Wood" => "Pat Donahue" },
        15 => { "Todd Chapin" => "Bobby Kilgus",
                 "Paul Percuoco" => "Pete Linstrom",
                 "Rick Wood" => "Pat Donahue" },
    },
    2019 => {
        1 => { "Rick Wood" => "Tony Albertini",
               "Steve Calvao" => "Jim O'Keefe",
               "Todd Chapin" => "John Breslouf" },
        2 => { "Todd Chapin" => "Kevin Cunningham",
               "Alex Williams" => "Marc Foland",
               "David Correia" => "Dan Correia",
               "Joe Graceffa" => "Ray Curley",
               "Rick Wood" => "Tony Albertini" },
        3 => { "Rick Wood" => "Tony Albertini",
               "Steve Calvao" => "Jim O'Keefe" },
        4 => { "Joe Graceffa" => "Tom Curley",
               "Rick Wood" => "Tony Albertini" },
        5 => { "Alex Williams" => "Randy Carter",
               "Steve Calvao" => "Tony Albertini" },
        6 => { "Chris DiSilva" => "Charlie Bacon",
               "Alex Williams" => "Mike Perisho",
               "Steve Calvao" => "Tony Albertini" },
        7 => { "Alex Williams" => "Marc Foland",
               "Steve Calvao" => "Tony Albertini",
               "Leo Palatino" => "Pat Donahue" },
        8 => { "Paul Percuoco" => "Scott O'Connor",
               "Steve Calvao" => "Tony Albertini",
               "Alex Williams" => "Kevin Kittredge" },
        9 => { "Steve Calvao" => "Tony Albertini",
               "Alex Williams" => "Mike Gill",
               "Carl Humphreys" => "Charlie Weeks" },
        10 => { "Alex Williams" => "Jim O'Keefe",
                "Leo Palatino" => "Pat Donahue",
                "Steve Calvao" => "Tony Albertini" },
        11 => { "Jeff LaPlante" => "Kevin Cunningham",
                "Leo Palatino" => "Joe Sullivan",
                "Todd Chapin" => "Derek Jodoin",
                "Steve Calvao" => "Tony Albertini" },
        12 => { "Alex Williams" => "Tony Albertini",
                "Leo Palatino" => "Dan Correia",
                "Paul Percuoco" => "Paul Sirois",
                "Todd Chapin" => "Bobby Kilgus" },
        13 => { "Jeff LaPlante" => "Mike Perisho",
                "Todd Chapin" => "Bobby Kilgus",
                "Leo Palatino" => "Joe Sullivan",
                "Steve Calvao" => "Tony Albertini",
                "Alex Williams" => "Jeff Miller",
                "Joe Graceffa" => "Tom Curley" },
        14 => { "Steve Calvao" => "Tony Albertini",
                "Alex Williams" => "Kevin Kittredge" },
        15 => { "Leo Palatino" => "Pat Donahue",
                "Alex Williams" => "Mike Gill" },
    },
    2020 => {
        1 => { "Carl Humphreys" => "Charlie Weeks",
               "Derek Palatino" => "Paul Correia" },
        2 => { "Derek Palatino" => "Paul Correia" },
        3 => { "Derek Palatino" => "Paul Correia" },
        4 => { "Pat Donahue II" => "Joe Sullivan",
               "Derek Palatino" => "Paul Correia" },
        5 => { "Derek Palatino" => "Paul Correia" },
        6 => { "Derek Palatino" => "Charlie Weeks" },
        7 => { "Jeff LaPlante" => "Mike Perisho" },
        8 => { "Jeff LaPlante" => "Mike Perisho",
               "Carl Humphreys" => "Charlie Weeks" },
        9 => { "Carl Humphreys" => "Charlie Weeks" },
        10 => { "Derek Palatino" => "Marc Foland",
                "Carl Humphreys" => "Charlie Weeks",
                "Brian Sargent" => "Jim Marotta",
                "Leo Palatino" => "Pat Donahue" },
        11 => { "Todd Chapin" => "Paul Sirois",
                "Carl Humphreys" => "Charlie Weeks",
                "Derek Palatino" => "Derek Jodoin" },
        12 => { "Todd Chapin" => "Kevin Cunningham",
                "Jeff LaPlante" => "Jeff Miller" },
        13 => { "Derek Palatino" => "Mike Schmidt",
                "Steve Calvao" => "Kevin Kittredge",
                "Leo Palatino" => "Dan Correia" },
        14 => { },
        15 => { "Derek Palatino" => "Bob Tuttle",
                "Steve Calvao" => "Kevin Kittredge" },
    },
    2021 => {
        1 => { "Derek Palatino" => "Dan Correia",
               "Leo Palatino" => "Paul Correia",
               "Ron Melanson" => "Steve Bulawka" },
        2 => { "Derek Palatino" => "Dan Correia",
               "Leo Palatino" => "Paul Correia",
               "Ron Melanson" => "Steve Bulawka" },
        3 => { "Derek Palatino" => "Dan Correia",
               "Leo Palatino" => "Paul Correia",
               "Ron Melanson" => "Steve Bulawka" },
        4 => { "Derek Palatino" => "Dan Correia",
               "Leo Palatino" => "Paul Correia",
               "Alex Williams" => "Marc Foland",
               "Rick Wood" => "Jim O'Keefe",
               "Todd Chapin" => "Derek Jodoin",
               "Ron Melanson" => "Steve Bulawka" },
        5 => { "Derek Palatino" => "Scott O'Connor",
               "Ron Melanson" => "Steve Bulawka" },
        6 => { "Carl Humphreys" => "Charlie Weeks",
               "Ron Melanson" => "Steve Bulawka" },
        7 => { "Ron Melanson" => "Steve Bulawka" },
        8 => { "Ben Palatino" => "Mike Gill",
               "Jeff Aucoin" => "Bob Tuttle",
               "Ron Melanson" => "Steve Bulawka" },
        9 => { "Derek Palatino" => "Pat Donahue",
               "Peter Bradley" => "Mike Perisho",
               "Jeff LaPlante" => "Kevin Cunningham",
               "Curt Farnsworth" => "Steve Bulawka" },
        10 => { "Leo Palatino" => "Jim Marotta",
                "Steve Calvao" => "Mike Gill",
                "Rick Wood" => "Jim O'Keefe",
                "Buddy Cuozzo" => "Kevin Cunningham",
                "Paul Rotker" => "Charlie Weeks",
                "Ron Melanson" => "Steve Bulawka",
                "Derek Palatino" => "Dan Correia",
                "Ray Curley" => "Tom Curley" },
        11 => { "Leo Palatino" => "Charlie Weeks",
                "Bill Andon" => "Mike Schmidt",
                "Steve Calvao" => "Randy Carter",
                "Rick Wood" => "Marc Foland",
                "Ron Melanson" => "Steve Bulawka",
                "Derek Palatino" => "Mike Rogers" },
        12 => { "Leo Palatino" => "Paul Sirois",
                "Carl Humphreys" => "Charlie Weeks",
                "Alex Williams" => "Joe Graceffa",
                "Jeff Aucoin" => "Bob Tuttle" },
        13 => { "Leo Palatino" => "Jim Marotta",
                "Carl Humphreys" => "Charlie Weeks",
                "Jeff Aucoin" => "Jeff Miller" },
        14 => { "Pat Donahue II" => "Joe Sullivan",
                "Brian Sargent" => "Tony Albertini",
                "Leo Palatino" => "Paul Sirois",
                "Dave Sherman" => "Larry Fryatt",
                "Ron Melanson" => "John Breslouf",
                "Jeff LaPlante" => "Mike Perisho",
                "Todd Chapin" => "Bobby Kilgus",
                "Carl Humphreys" => "Charlie Weeks" },
        15 => { "Bill Andon" => "Charlie Weeks",
                "Leo Palatino" => "Mike Schmidt",
                "Curt Farnsworth" => "John Breslouf",
                "Todd Chapin" => "Bobby Kilgus",
                "Buddy Cuozzo" => "Derek Jodoin",
                "Ray Curley" => "Marc Foland" },
    },
    2022 => {
        1 => { "Carl Humphreys" => "Charlie Weeks",
               "Derek Palatino" => "Paul Correia",
               "Jeff Aucoin" => "Bob Tuttle",
               "Jeff LaPlante" => "Mike Perisho" },
        2 => { "Carl Humphreys" => "Charlie Weeks",
               "Derek Palatino" => "Paul Correia",
               "Joe Graceffa" => "Paul Percuoco",
               "Jeff LaPlante" => "Mike Perisho" },
        3 => { "Carl Humphreys" => "Charlie Weeks",
               "Derek Palatino" => "Paul Correia",
               "Leo Palatino" => "Paul Percuoco",
               "Jeff Aucoin" => "Bob Tuttle" },
        4 => { "Carl Humphreys" => "Charlie Weeks",
               "Derek Palatino" => "Paul Percuoco",
               "Leo Palatino" => "Chet Czapkowski",
               "Todd Chapin" => "Derek Jodoin",
               "Joe Graceffa" => "Jeff Miller",
               "Jeff LaPlante" => "Bob Tuttle" },
        5 => { "Jeff Aucoin" => "Bob Tuttle" },
        6 => { "Carl Humphreys" => "Charlie Weeks",
               "Jeff Aucoin" => "Bob Tuttle" },
        7 => { "Leo Palatino" => "Jim O'Keefe",
               "Joe Graceffa" => "Ray Curley" },
        8 => { "Carl Humphreys" => "Charlie Weeks" },
        9 => { "Phil Treen" => "John Breslouf",
               "Alex Williams" => "Tony Albertini" },
        10 => { "Derek Palatino" => "Mike Schmidt",
                "Rick Wood" => "Jim O'Keefe" },
        11 => { "Carl Purinton" => "Jim Marotta",
                "Todd Chapin" => "Charlie Weeks",
                "Jeff Aucoin" => "Mike Gill",
                "Jeff LaPlante" => "Kevin Cunningham",
                "Rick Wood" => "Jim O'Keefe" },
        12 => { "Jeff Aucoin" => "Jeff Miller",
                "Derek Palatino" => "Charlie Weeks",
                "Rick Wood" => "Kevin Kittredge" },
        13 => { "Carl Humphreys" => "Charlie Weeks",
                "Jeff LaPlante" => "Kevin Cunningham",
                "Buddy Cuozzo" => "Paul Sirois",
                "Derek Palatino" => "Joe Sullivan",
                "Leo Palatino" => "Pat Donahue" },
        14 => { "Carl Humphreys" => "Charlie Weeks",
                "Leo Palatino" => "Jim Marotta",
                "Jeff LaPlante" => "Mike Perisho" },
        15 => { "Jeff Aucoin" => "Jeff Miller",
                "Joe Graceffa" => "Ray Curley",
                "Todd Chapin" => "Bobby Kilgus" },
    },
    2023 => {
        1 => { "Paul Rotker" => "Charlie Weeks",
               "Jeff LaPlante" => "Mike Perisho",
               "Dave Sherman" => "Charlie Bacon",
               "Leo Palatino" => "Paul Correia" },
        2 => { "Leo Palatino" => "Paul Correia" },
        3 => { "Alex Williams" => "Mike Gill",
               "Steve Calvao" => "Randy Carter",
               "Brian Sargent" => "Tom Curley",
               "Joe Graceffa" => "Bob Tuttle",
               "Leo Palatino" => "Paul Correia",
               "Ron Melanson" => "John Breslouf" },
        4 => { "Leo Palatino" => "Chet Czapkowski",
               "Brian Sargent" => "Marc Foland",
               "Alex Williams" => "Jeff Miller",
               "Ron Melanson" => "John Breslouf",
               "Joe Graceffa" => "Bob Tuttle",
               "Steve Calvao" => "Pat Donahue" },
        5 => { "Leo Palatino" => "Dan Correia",
               "Brian Sargent" => "Marc Foland",
               "Ron Melanson" => "John Breslouf" },
        6 => { "Leo Palatino" => "Dan Correia",
               "Paul Rotker" => "Charlie Weeks", },
        7 => { "Derek Palatino" => "Dan Correia",
               "Brian Sargent" => "Paul Percuoco",
               "Steve Calvao" => "Jim O'Keefe" },
        8 => { "Derek Palatino" => "Pat Donahue",
               "Joe Graceffa" => "Bob Tuttle",
               "Alex Williams" => "Jeff Miller" },
        9 => { "Todd Chapin" => "Derek Jodoin",
               "Derek Palatino" => "Paul Sirois",
               "Rick Wood" => "Randy Carter",
               "Alex Williams" => "Pete Linstrom" },
        10 => { "Leo Palatino" => "Paul Sirois",
                "Bob Donahue" => "Joe Sullivan",
                "Steve Willey" => "Pete Linstrom" },
        11 => { "Steve Willey" => "Pete Linstrom",
                "Rick Wood" => "Randy Carter",
                "Paul Rotker" => "Charlie Weeks",
                "Leo Palatino" => "Jim Marotta",
                "Alex Williams" => "John Maley" },
        12 => { "Buddy Cuozzo" => "Paul Sirois",
                "Paul Rotker" => "Charlie Weeks",
                "Leo Palatino" => "Paul Correia",
                "Bill Andon" => "Dan Correia",
                "Bob Donahue" => "Joe Sullivan",
                "Todd Chapin" => "Derek Jodoin" },
        13 => { "Paul Rotker" => "Charlie Weeks",
                "Leo Palatino" => "Dan Correia" },
        14 => { "Paul Rotker" => "Charlie Weeks",
                "Steve Willey" => "Pete Linstrom",
                "Bob Donahue" => "Joe Sullivan",
                "Jeff Aucoin" => "Jeff Miller",
                "Alex Williams" => "Mike Rogers",
                "Bill Andon" => "Dan Correia",
                "Joe Graceffa" => "Ray Curley",
                "Kevin Kittredge Jr" => "Tony Albertini",
                "Leo Palatino" => "Paul Correia" },
        15 => { "Paul Rotker" => "Charlie Weeks",
                "Dave Sherman" => "Charlie Bacon",
                "Jeff LaPlante" => "Mike Perisho",
                "Todd Chapin" => "Bobby Kilgus" },
    },
    2024 => {
        1 => { "Ben Palatino" => "Paul Correia",
               "Brian Sargent" => "Marc Foland",
               "Joe Graceffa" => "Bob Donahue",
               "Alex Williams" => "Paul Percuoco",
               "Jeff LaPlante" => "Mike Perisho" },
        2 => { "Leo Palatino" => "Paul Percuoco",
               "Jeff LaPlante" => "Mike Perisho" },
        3 => { "Jeff LaPlante" => "Mike Perisho",
               "Todd Chapin" => "Paul Percuoco",
               "Paul Rotker" => "Derek Jodoin",
               "Ryan Tuttle" => "Jeff Miller",
               "Leo Palatino" => "Chet Czapkowski" },
        4 => { "Jeff LaPlante" => "Mike Perisho",
               "Paul Rotker" => "Mike Schmidt",
               "Alex Williams" => "Tom Curley",
               "Buddy Cuozzo" => "Paul Sirois",
               "Todd Chapin" => "Paul Percuoco" },
        #6 => { "Ben Palatino" => "Mike Gill" },
    },
);
