%t = (
    "TNFB/East/Black Bears"    => { 1 => "Cunningham, Kevin", 2 => "Perisho, Mike" },
    "TNFB/East/Eagles"         => { 1 => "Correia, Paul", 2 => "Correia, Dan" },
    "TNFB/East/Huskies"        => { 1 => "Rogers, Mike", 2 => "Maley, John" },
    "TNFB/East/Minutemen"      => { 1 => "Curley, Tom", 2 => "Curley, Ray" },
    "TNFB/East/River Hawks"    => { 1 => "Czapkowski, Chet", 2 => "Marotta, Jim" },
    "TNFB/East/Terriers"       => { 1 => "O'Connor, Scott", 2 => "Treen, Phil" },
    "TNFB/East/Warriors"       => { 1 => "Donahue, Pat", 2 => "Sullivan, Joe" },
    "TNFB/East/Wildcats"       => { 1 => "Carter, Randy", 2 => "O'Keefe, Jim" },
    "TNFB/West/Badgers"        => { 1 => "Kilgus, Bob", 2 => "Jodoin, Derek" },
    "TNFB/West/Buckeyes"       => { 1 => "Bacon, Charlie", 2 => "Fryatt, Larry" },
    "TNFB/West/Bulldogs"       => { 1 => "Gill, Mike", 2 => "Foland, Marc" },
    "TNFB/West/Fighting Sioux" => { 1 => "Albertini, Tony", 2 => "Kittredge, Kevin" },
    "TNFB/West/Golden Gofers"  => { 1 => "Breslouf, John", 2 => "Bulawka, Steve" },
    "TNFB/West/Pioneers"       => { 1 => "Tuttle, Bob", 2 => "Miller, Jeff" },
    "TNFB/West/Seawolves"      => { 1 => "Weeks, Charlie", 2 => "Schmidt, Mike" },
    "TNFB/West/Tigers"         => { 1 => "Linstrom, Pete", 2 => "Sirois, Paul" },
);

%golfers = (
    "golfers/099.ID" => { name => "Tony Albertini", team => "TNFB/West/Fighting Sioux", active => 1 },
    "golfers/069.ID" => { name => "Charlie Bacon", team => "TNFB/West/Buckeyes", active => 1 },
    "golfers/067.ID" => { name => "John Breslouf", team => "TNFB/West/Golden Gofers", active => 1 },
    "golfers/073.ID" => { name => "Steve Bulawka", team => "TNFB/West/Golden Gofers", active => 1 },
    "golfers/021.ID" => { name => "Randy Carter", team => "TNFB/East/Wildcats", active => 1 },
    "golfers/080.ID" => { name => "Dan Correia", team => "TNFB/East/Eagles", active => 1 },
    "golfers/072.ID" => { name => "Paul Correia", team => "TNFB/East/Eagles", active => 1 },
    "golfers/042.ID" => { name => "Kevin Cunningham", team => "TNFB/East/Black Bears", active => 1 },
    "golfers/078.ID" => { name => "Ray Curley", team => "TNFB/East/Minutemen", active => 1 },
    "golfers/082.ID" => { name => "Tom Curley", team => "TNFB/East/Minutemen", active => 1 },
    "golfers/020.ID" => { name => "Chet Czapkowski", team => "TNFB/East/River Hawks", active => 1 },
    "golfers/011.ID" => { name => "Pat Donahue", team => "TNFB/East/Warriors", active => 1 },
    "golfers/038.ID" => { name => "Marc Foland", team => "TNFB/West/Bulldogs", active => 1 },
    "golfers/070.ID" => { name => "Larry Fryatt", team => "TNFB/West/Buckeyes", active => 1 },
    "golfers/027.ID" => { name => "Mike Gill", team => "TNFB/West/Bulldogs", active => 1 },
    "golfers/095.ID" => { name => "Derek Jodoin", team => "TNFB/West/Badgers", active => 1 },
    "golfers/081.ID" => { name => "Bob Kilgus", team => "TNFB/West/Badgers", active => 1 },
    "golfers/024.ID" => { name => "Kevin Kittredge", team => "TNFB/West/Fighting Sioux", active => 1 },
    "golfers/047.ID" => { name => "Pete Linstrom", team => "TNFB/West/Tigers", active => 1 },
    "golfers/046.ID" => { name => "John Maley", team => "TNFB/East/Huskies", active => 1 },
    "golfers/017.ID" => { name => "Jim Marotta", team => "TNFB/East/River Hawks", active => 1 },
    "golfers/094.ID" => { name => "Jeff Miller", team => "TNFB/West/Pioneers", active => 1 },
    "golfers/001.ID" => { name => "Scott O'Connor", team => "TNFB/East/Terriers", active => 1 },
    "golfers/035.ID" => { name => "Jim O'Keefe", team => "TNFB/East/Wildcats", active => 1 },
    "golfers/093.ID" => { name => "Mike Perisho", team => "TNFB/East/Black Bears", active => 1 },
    "golfers/090.ID" => { name => "Mike Rogers", team => "TNFB/East/Huskies", active => 1 },
    "golfers/010.ID" => { name => "Mike Schmidt", team => "TNFB/West/Seawolves", active => 1 },
    "golfers/060.ID" => { name => "Paul Sirois", team => "TNFB/West/Tigers", active => 1 },
    "golfers/034.ID" => { name => "Joe Sullivan", team => "TNFB/East/Warriors", active => 1 },
    "golfers/002.ID" => { name => "Phil Treen", team => "TNFB/East/Terriers", active => 1 },
    "golfers/054.ID" => { name => "Bob Tuttle", team => "TNFB/West/Pioneers", active => 1 },
    "golfers/009.ID" => { name => "Charlie Weeks", team => "TNFB/West/Seawolves", active => 1 },
    "golfers/136.ID" => { name => "Ryan Abrams", team => "Sub", active => 1 },
    "golfers/129.ID" => { name => "Jeff Aucoin", team => "Sub", active => 1 },
    "golfers/109.ID" => { name => "Mike Baj", team => "Sub", active => 1 },
    "golfers/114.ID" => { name => "Tim Benson", team => "Sub", active => 1 },
    "golfers/056.ID" => { name => "Joe Berry", team => "Sub", active => 1 },
    "golfers/023.ID" => { name => "Vic Billings", team => "Sub", active => 1 },
    "golfers/015.ID" => { name => "Wayne Bolivar", team => "Sub", active => 1 },
    "golfers/098.ID" => { name => "Rick Butts", team => "Sub", active => 1 },
    "golfers/138.ID" => { name => "Phil Bz", team => "Sub", active => 1 },
    "golfers/059.ID" => { name => "Cliff Calvao", team => "Sub", active => 1 },
    "golfers/062.ID" => { name => "Steve Calvao", team => "Sub", active => 1 },
    "golfers/116.ID" => { name => "Charles Centore", team => "Sub", active => 1 },
    "golfers/134.ID" => { name => "Steve Cerven", team => "Sub", active => 1 },
    "golfers/117.ID" => { name => "Paul Chaisson", team => "Sub", active => 1 },
    "golfers/052.ID" => { name => "Todd Chapin", team => "Sub", active => 1 },
    "golfers/014.ID" => { name => "David Correia", team => "Sub", active => 1 },
    "golfers/005.ID" => { name => "Kevin Crowley", team => "Sub", active => 1 },
    "golfers/048.ID" => { name => "Buddy Cuozzo", team => "Sub", active => 1 },
    "golfers/006.ID" => { name => "Gerry Curley", team => "Sub", active => 1 },
    "golfers/103.ID" => { name => "Kevin Cyr", team => "Sub", active => 1 },
    "golfers/016.ID" => { name => "Tom Czarkowski", team => "Sub", active => 1 },
    "golfers/053.ID" => { name => "Chris Deehan", team => "Sub", active => 1 },
    "golfers/055.ID" => { name => "Dave DellePenna", team => "Sub", active => 1 },
    "golfers/132.ID" => { name => "John Desisto", team => "Sub", active => 1 },
    "golfers/130.ID" => { name => "Chris DiSilva Sr", team => "Sub", active => 1 },
    "golfers/122.ID" => { name => "Chris DiSilva", team => "Sub", active => 1 },
    "golfers/125.ID" => { name => "Phil Doe", team => "Sub", active => 1 },
    "golfers/039.ID" => { name => "Mark Donahue", team => "Sub", active => 1 },
    "golfers/111.ID" => { name => "Rick Dowen", team => "Sub", active => 1 },
    "golfers/102.ID" => { name => "Mike Durand", team => "Sub", active => 1 },
    "golfers/089.ID" => { name => "Bill Egan", team => "Sub", active => 1 },
    "golfers/040.ID" => { name => "Mike Elkort", team => "Sub", active => 1 },
    "golfers/036.ID" => { name => "John Emerson", team => "Sub", active => 1 },
    "golfers/101.ID" => { name => "Ray Emond", team => "Sub", active => 1 },
    "golfers/108.ID" => { name => "Grant Everett", team => "Sub", active => 1 },
    "golfers/026.ID" => { name => "Scott Fairbairn", team => "Sub", active => 1 },
    "golfers/087.ID" => { name => "John Fitzgerald", team => "Sub", active => 1 },
    "golfers/096.ID" => { name => "Joe Flannery", team => "Sub", active => 1 },
    "golfers/018.ID" => { name => "Jay Fredette", team => "Sub", active => 1 },
    "golfers/137.ID" => { name => "Carl Fryatt", team => "Sub", active => 1 },
    "golfers/112.ID" => { name => "Mike Fz", team => "Sub", active => 1 },
    "golfers/037.ID" => { name => "Paul Giancola", team => "Sub", active => 1 },
    "golfers/110.ID" => { name => "Tim Gleason", team => "Sub", active => 1 },
    "golfers/051.ID" => { name => "Andrew Goddard", team => "Sub", active => 1 },
    "golfers/004.ID" => { name => "Joe Graceffa", team => "Sub", active => 1 },
    "golfers/028.ID" => { name => "Jim Gregg", team => "Sub", active => 1 },
    "golfers/022.ID" => { name => "Richard Guild", team => "Sub", active => 1 },
    "golfers/074.ID" => { name => "Sean Hanley", team => "Sub", active => 1 },
    "golfers/012.ID" => { name => "Bruce Harris", team => "Sub", active => 1 },
    "golfers/135.ID" => { name => "Matt Herring", team => "Sub", active => 1 },
    "golfers/013.ID" => { name => "Carl Humphreys", team => "Sub", active => 1 },
    "golfers/107.ID" => { name => "Jeff Kerrigan", team => "Sub", active => 1 },
    "golfers/029.ID" => { name => "Jeff LaPlante", team => "Sub", active => 1 },
    "golfers/104.ID" => { name => "Steve LaRosee", team => "Sub", active => 1 },
    "golfers/086.ID" => { name => "Paul LeBlanc", team => "Sub", active => 1 },
    "golfers/100.ID" => { name => "Ken Leigh", team => "Sub", active => 1 },
    "golfers/043.ID" => { name => "Al Litchfield", team => "Sub", active => 1 },
    "golfers/113.ID" => { name => "Mike Manere", team => "Sub", active => 1 },
    "golfers/079.ID" => { name => "Dave Maruska", team => "Sub", active => 1 },
    "golfers/124.ID" => { name => "Bob Mauro", team => "Sub", active => 1 },
    "golfers/091.ID" => { name => "Mark McAleese", team => "Sub", active => 1 },
    "golfers/085.ID" => { name => "John McCauley", team => "Sub", active => 1 },
    "golfers/033.ID" => { name => "Mike McPoland", team => "Sub", active => 1 },
    "golfers/068.ID" => { name => "Don Moorehead", team => "Sub", active => 1 },
    "golfers/120.ID" => { name => "Charles Nolfi", team => "Sub", active => 1 },
    "golfers/077.ID" => { name => "Dave O'Donnell", team => "Sub", active => 1 },
    "golfers/115.ID" => { name => "Peter O'Hearn", team => "Sub", active => 1 },
    "golfers/066.ID" => { name => "Eric Ogren", team => "Sub", active => 1 },
    "golfers/119.ID" => { name => "Pat Osborne", team => "Sub", active => 1 },
    "golfers/007.ID" => { name => "Leo Palatino", team => "Sub", active => 1 },
    "golfers/019.ID" => { name => "Paul Percuoco", team => "Sub", active => 1 },
    "golfers/025.ID" => { name => "Tom Percuoco", team => "Sub", active => 1 },
    "golfers/050.ID" => { name => "Ken Pesanelli", team => "Sub", active => 1 },
    "golfers/071.ID" => { name => "Dave Petkauskos", team => "Sub", active => 1 },
    "golfers/118.ID" => { name => "Mark Reid", team => "Sub", active => 1 },
    "golfers/097.ID" => { name => "Robert Reslow", team => "Sub", active => 1 },
    "golfers/092.ID" => { name => "Ed Reverdy", team => "Sub", active => 1 },
    "golfers/088.ID" => { name => "Tom Rothfuss", team => "Sub", active => 1 },
    "golfers/084.ID" => { name => "Mike Saliga", team => "Sub", active => 1 },
    "golfers/049.ID" => { name => "Brian Sargent", team => "Sub", active => 1 },
    "golfers/061.ID" => { name => "Joe Scorzelli", team => "Sub", active => 1 },
    "golfers/063.ID" => { name => "Eric Semple", team => "Sub", active => 1 },
    "golfers/128.ID" => { name => "Bob Sherman", team => "Sub", active => 1 },
    "golfers/123.ID" => { name => "Dave Sherman", team => "Sub", active => 1 },
    "golfers/057.ID" => { name => "Cliff Spates", team => "Sub", active => 1 },
    "golfers/030.ID" => { name => "Russ Spencer", team => "Sub", active => 1 },
    "golfers/003.ID" => { name => "David Spurr", team => "Sub", active => 1 },
    "golfers/065.ID" => { name => "Mark Starr", team => "Sub", active => 1 },
    "golfers/041.ID" => { name => "Mike Suleski", team => "Sub", active => 1 },
    "golfers/126.ID" => { name => "Phil Summers", team => "Sub", active => 1 },
    "golfers/031.ID" => { name => "Bill Swaney", team => "Sub", active => 1 },
    "golfers/045.ID" => { name => "Joe Thoman", team => "Sub", active => 1 },
    "golfers/105.ID" => { name => "Billy Tierney", team => "Sub", active => 1 },
    "golfers/131.ID" => { name => "Bill Tobey", team => "Sub", active => 1 },
    "golfers/075.ID" => { name => "Dan Toomey", team => "Sub", active => 1 },
    "golfers/133.ID" => { name => "Andy Treen", team => "Sub", active => 1 },
    "golfers/058.ID" => { name => "David Treen", team => "Sub", active => 1 },
    "golfers/083.ID" => { name => "Dan Warila", team => "Sub", active => 1 },
    "golfers/032.ID" => { name => "Dan Weilandt", team => "Sub", active => 1 },
    "golfers/121.ID" => { name => "Dan Welch", team => "Sub", active => 1 },
    "golfers/106.ID" => { name => "Don White", team => "Sub", active => 1 },
    "golfers/008.ID" => { name => "Joe White", team => "Sub", active => 1 },
    "golfers/076.ID" => { name => "Steve Willey", team => "Sub", active => 1 },
    "golfers/064.ID" => { name => "Alex Williams", team => "Sub", active => 1 },
    "golfers/127.ID" => { name => "Chris Williams", team => "Sub", active => 1 },
    "golfers/044.ID" => { name => "Rick Wood", team => "Sub", active => 1 },
);
