%golfers = (
	"golfers/099.ID" => { first => "Tony", last => "Albertini", team => "TNFB/West/Fighting Sioux" },
	"golfers/069.ID" => { first => "Charlie", last => "Bacon", team => "TNFB/West/Buckeyes" },
	"golfers/056.ID" => { first => "Joe", last => "Berry", team => "Sub" },
	"golfers/023.ID" => { first => "Vic", last => "Billings", team => "Sub" },
	"golfers/015.ID" => { first => "Wayne", last => "Bolivar", team => "Sub" },
	"golfers/067.ID" => { first => "John", last => "Breslouf", team => "TNFB/West/Golden Gofers" },
	"golfers/073.ID" => { first => "Steve", last => "Bulawka", team => "TNFB/West/Golden Gofers" },
	"golfers/098.ID" => { first => "Rick", last => "Butts", team => "Sub" },
	"golfers/059.ID" => { first => "Cliff", last => "Calvao", team => "Sub" },
	"golfers/062.ID" => { first => "Steve", last => "Calvao", team => "Sub" },
	"golfers/021.ID" => { first => "Randy", last => "Carter", team => "TNFB/East/Wildcats" },
	"golfers/052.ID" => { first => "Todd", last => "Chapin", team => "Sub" },
	"golfers/080.ID" => { first => "Dan", last => "Correia", team => "TNFB/East/Eagles" },
	"golfers/014.ID" => { first => "David", last => "Correia", team => "Sub" },
	"golfers/072.ID" => { first => "Paul", last => "Correia", team => "TNFB/East/Eagles" },
	"golfers/005.ID" => { first => "Kevin", last => "Crowley", team => "Sub" },
	"golfers/042.ID" => { first => "Kevin", last => "Cunningham", team => "TNFB/East/Black Bears" },
	"golfers/048.ID" => { first => "Buddy", last => "Cuozzo", team => "Sub" },
	"golfers/006.ID" => { first => "Gerry", last => "Curley", team => "Sub" },
	"golfers/078.ID" => { first => "Ray", last => "Curley", team => "TNFB/East/Minutemen" },
	"golfers/082.ID" => { first => "Tom", last => "Curley", team => "TNFB/East/Minutemen" },
	"golfers/020.ID" => { first => "Chet", last => "Czapkowski", team => "TNFB/East/River Hawks" },
	"golfers/016.ID" => { first => "Tom", last => "Czarkowski", team => "Sub" },
	"golfers/053.ID" => { first => "Chris", last => "Deehan", team => "Sub" },
	"golfers/055.ID" => { first => "Dave", last => "DellePenna", team => "Sub" },
	"golfers/039.ID" => { first => "Mark", last => "Donahue", team => "Sub" },
	"golfers/011.ID" => { first => "Pat", last => "Donahue", team => "TNFB/East/Warriors" },
	"golfers/040.ID" => { first => "Mike", last => "Elkort", team => "Sub" },
	"golfers/036.ID" => { first => "John", last => "Emerson", team => "Sub" },
	"golfers/026.ID" => { first => "Scott", last => "Fairbairn", team => "Sub" },
	"golfers/087.ID" => { first => "John", last => "Fitzgerald", team => "Sub" },
	"golfers/096.ID" => { first => "Joe", last => "Flannery", team => "Sub" },
	"golfers/038.ID" => { first => "Marc", last => "Foland", team => "TNFB/West/Bulldogs" },
	"golfers/018.ID" => { first => "Jay", last => "Fredette", team => "Sub" },
	"golfers/070.ID" => { first => "Larry", last => "Fryatt", team => "TNFB/West/Buckeyes" },
	"golfers/037.ID" => { first => "Paul", last => "Giancola", team => "Sub" },
	"golfers/027.ID" => { first => "Mike", last => "Gill", team => "TNFB/West/Bulldogs" },
	"golfers/051.ID" => { first => "Andrew", last => "Goddard", team => "Sub" },
	"golfers/004.ID" => { first => "Joe", last => "Graceffa", team => "Sub" },
	"golfers/028.ID" => { first => "Jim", last => "Gregg", team => "Sub" },
	"golfers/022.ID" => { first => "Richard", last => "Guild", team => "Sub" },
	"golfers/074.ID" => { first => "Sean", last => "Hanley", team => "Sub" },
	"golfers/012.ID" => { first => "Bruce", last => "Harris", team => "Sub" },
	"golfers/013.ID" => { first => "Carl", last => "Humphreys", team => "Sub" },
	"golfers/095.ID" => { first => "Derek", last => "Jodoin", team => "TNFB/West/Badgers" },
	"golfers/081.ID" => { first => "Bob", last => "Kilgus", team => "TNFB/West/Badgers" },
	"golfers/024.ID" => { first => "Kevin", last => "Kittredge", team => "TNFB/West/Fighting Sioux" },
	"golfers/029.ID" => { first => "Jeff", last => "LaPlante", team => "Sub" },
	"golfers/086.ID" => { first => "Paul", last => "LeBlanc", team => "Sub" },
	"golfers/047.ID" => { first => "Pete", last => "Linstrom", team => "TNFB/West/Tigers" },
	"golfers/043.ID" => { first => "Al", last => "Litchfield", team => "Sub" },
	"golfers/046.ID" => { first => "John", last => "Maley", team => "TNFB/East/Huskies" },
	"golfers/017.ID" => { first => "Jim", last => "Marotta", team => "TNFB/East/River Hawks" },
	"golfers/079.ID" => { first => "Dave", last => "Maruska", team => "Sub" },
	"golfers/091.ID" => { first => "Mark", last => "McAleese", team => "Sub" },
	"golfers/085.ID" => { first => "John", last => "McCauley", team => "Sub" },
	"golfers/033.ID" => { first => "Mike", last => "McPoland", team => "Sub" },
	"golfers/094.ID" => { first => "Jeff", last => "Miller", team => "TNFB/West/Pioneers" },
	"golfers/068.ID" => { first => "Don", last => "Moorehead", team => "Sub" },
	"golfers/001.ID" => { first => "Scott", last => "O'Connor", team => "TNFB/East/Terriers" },
	"golfers/077.ID" => { first => "Dave", last => "O'Donnell", team => "Sub" },
	"golfers/035.ID" => { first => "Jim", last => "O'Keefe", team => "TNFB/East/Wildcats" },
	"golfers/066.ID" => { first => "Eric", last => "Ogren", team => "Sub" },
	"golfers/007.ID" => { first => "Leo", last => "Palatino", team => "Sub" },
	"golfers/019.ID" => { first => "Paul", last => "Percuoco", team => "Sub" },
	"golfers/025.ID" => { first => "Tom", last => "Percuoco", team => "Sub" },
	"golfers/093.ID" => { first => "Mike", last => "Perisho", team => "TNFB/East/Black Bears" },
	"golfers/050.ID" => { first => "Ken", last => "Pesanelli", team => "Sub" },
	"golfers/071.ID" => { first => "Dave", last => "Petkauskos", team => "Sub" },
	"golfers/097.ID" => { first => "Robert", last => "Reslow", team => "Sub" },
	"golfers/092.ID" => { first => "Ed", last => "Reverdy", team => "Sub" },
	"golfers/090.ID" => { first => "Mike", last => "Rogers", team => "TNFB/East/Huskies" },
	"golfers/088.ID" => { first => "Tom", last => "Rothfuss", team => "Sub" },
	"golfers/084.ID" => { first => "Mike", last => "Saliga", team => "Sub" },
	"golfers/049.ID" => { first => "Brian", last => "Sargent", team => "Sub" },
	"golfers/010.ID" => { first => "Mike", last => "Schmidt", team => "TNFB/West/Seawolves" },
	"golfers/063.ID" => { first => "Eric", last => "Semple", team => "Sub" },
	"golfers/060.ID" => { first => "Paul", last => "Sirois", team => "TNFB/West/Tigers" },
	"golfers/003.ID" => { first => "David", last => "Spurr", team => "Sub" },
	"golfers/065.ID" => { first => "Mark", last => "Starr", team => "Sub" },
	"golfers/041.ID" => { first => "Mike", last => "Suleski", team => "Sub" },
	"golfers/034.ID" => { first => "Joe", last => "Sullivan", team => "TNFB/East/Warriors" },
	"golfers/031.ID" => { first => "Bill", last => "Swaney", team => "Sub" },
	"golfers/045.ID" => { first => "Joe", last => "Thoman", team => "Sub" },
	"golfers/058.ID" => { first => "David", last => "Treen", team => "Sub" },
	"golfers/002.ID" => { first => "Phil", last => "Treen", team => "TNFB/East/Terriers" },
	"golfers/054.ID" => { first => "Bob", last => "Tuttle", team => "TNFB/West/Pioneers" },
	"golfers/083.ID" => { first => "Dan", last => "Warila", team => "Sub" },
	"golfers/009.ID" => { first => "Charlie", last => "Weeks", team => "TNFB/West/Seawolves" },
	"golfers/032.ID" => { first => "Dan", last => "Weilandt", team => "Sub" },
	"golfers/008.ID" => { first => "Joe", last => "White", team => "Sub" },
	"golfers/076.ID" => { first => "Steve", last => "Willey", team => "Sub" },
	"golfers/064.ID" => { first => "Alex", last => "Williams", team => "Sub" },
	"golfers/044.ID" => { first => "Rick", last => "Wood", team => "Sub" },
);
